### PR TITLE
Adding some changes to our markup.This should be our initial skeleton.

### PR DESCRIPTION
**Pull request by anand92490**
Please review.

### CODE REVIEW

**Review by jjohns2 — CHANGES_REQUESTED** [review]
This is looking good! 

I noticed that all the ids have a value of "dropdownMenu2". Could you go through and give them unique ids? The placement of the ids are perfect, they simply need to be given unique names. Thinking ahead to when we take these inputs from the DOM and using them to call specific information from the APIs, we will need unique identifiers. 

I think Vince had the price range in his AJAX call from $0 to $500. We will have to coordinate them eventually. For now, I would keep it as is. I'm simply writing this down as a reminder to myself.

Thank you for your work on this!

**Comment by anand92490** [comment]
I'm glad you brought it up. I'll get it done and push the changes. Those id's are the default bootstrap id's and was unsure what to do with it.

**Comment by jjohns2** [comment]
If the id is from bootstrap, it's possible that bootstrap is using that specific id to link to the bootstrap js script. I'm not 100% sure, and I'm not near my laptop right now to check. If the dropdown is breaking with the id's change, then I would keep the ids and add another id for our specific JS files. We can also go over this tomorrow in class!

**Comment by anand92490** [comment]
Sure!

**Review by jjohns2 — APPROVED** [review]
Thanks!!

**Pull request merged**
